### ISSUE TITLE
Error after updating to the latest version

### ISSUE THREAD

**Issue by tiredoftry** [tjoen/skill-better-jokes#2]
MyCroft auto-updated on 5/17/2018 and now better-jokes gives and error 'Any error occurred processing a reqest in better jokes skills'.

I would assume this is due to MyCroft going from Python 2.7 to 3.4+.

**Comment by tjoen** [comment]
Thanks for posting the issue.  I'll adjust the skill asap, could take a couple of days before I have some time ;)

**Comment by tjoen** [comment]
This should be fixed now.

**Comment by tiredoftry** [comment]
Confirmed, it is working.  Thanks for the skill and for quick resolution.
